### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by Fuzion24** [isacikgoz/gitin#24]
```
No results
qpanic: runtime error: index out of range

goroutine 243 [running]:
github.com/isacikgoz/promptui/list.(*List).Index(0xc0000ac730, 0xc000000071)
	/Users/ibrahim/go/src/github.com/isacikgoz/promptui/list/list.go:204 +0x67
github.com/isacikgoz/promptui.(*Select).innerRun.func1(0xc01b3eefd8, 0x1, 0x1, 0x1, 0xc000000071, 0x)
	/Users/ibrahim/go/src/github.com/isacikgoz/promptui/select.go:340 +0x9a3
github.com/chzyer/readline.(*DumpListener).OnChange(0xc0000a2338, 0xc01b3eefd8, 0x1, 0x1, 0x1, 0x71,)
	/Users/ibrahim/go/src/github.com/chzyer/readline/operation.go:516 +0x63
github.com/chzyer/readline.(*Operation).ioloop(0xc02424b340)
	/Users/ibrahim/go/src/github.com/chzyer/readline/operation.go:339 +0x397
created by github.com/chzyer/readline.NewOperation
	/Users/ibrahim/go/src/github.com/chzyer/readline/operation.go:88 +0x2b1
```

**Comment by isacikgoz** [comment]
Thanks for the feedback @Fuzion24 can you tell me how did you got this error? Which subcommand you've used to start gitin?

**Comment by Fuzion24** [comment]
`gitin log` on the linux kernel

**Comment by isacikgoz** [comment]
I've also cloned linux kernel and tried to scroll, -the performance was not good tho- but couldn't reproduce. Maybe it is specific for a commit.

**Comment by isacikgoz** [comment]
Closing this issue due to inactivity. We can re-open this if we encounter with an issue like this.

**Comment by Fuzion24** [comment]
yea, sorry. I tried to reproduce, not sure what specific commit actually caused it.  It's quite slow to navigate through linux with gitin.  maybe that is worth looking into.

**Comment by isacikgoz** [comment]
Yeah, I will look for performance improvement after I finish the general frame of the tool. Linux kernel is also my reference too. Thanks for the feedback @Fuzion24
