### ISSUE TITLE
Panic when selecting on empty search result

### ISSUE THREAD

**Issue by CGA1123** [isacikgoz/gitin#52]
Reproduce:
`gitin log`
`/`
`type in some gibberish returning no results`
`<enter>`
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/isacikgoz/gitin/prompt.(*Log).onSelect(0xc0000d4500, 0xc0000e3d50)
	/Users/ibrahim/git/gitin/prompt/log.go:62 +0x3be
github.com/isacikgoz/gitin/prompt.(*prompt).assignKey(0xc0000a8140, 0xc00000000a, 0x2)
	/Users/ibrahim/git/gitin/prompt/prompt.go:203 +0xee
github.com/isacikgoz/gitin/prompt.(*prompt).innerRun(0xc0000a8140, 0x4432ab0, 0xc0000a8140)
	/Users/ibrahim/git/gitin/prompt/prompt.go:143 +0x19f
github.com/isacikgoz/gitin/prompt.(*prompt).start(0xc0000a8140, 0x0, 0x0)
	/Users/ibrahim/git/gitin/prompt/prompt.go:111 +0x241
github.com/isacikgoz/gitin/prompt.(*Log).Start(0xc0000d4500, 0xc0000d8cc0, 0x4399800, 0xc0000f0190)
	/Users/ibrahim/git/gitin/prompt/log.go:55 +0x3fd
main.run(0x442272b, 0x3, 0xc000016104, 0x32, 0x4, 0xc0000ea3f0)
	/Users/ibrahim/git/gitin/main.go:71 +0x29e
main.main()
	/Users/ibrahim/git/gitin/main.go:24 +0x69
```

I think this is unsafe accessing here:  https://github.com/isacikgoz/gitin/blob/master/prompt/log.go#L62

Awesome tool! This is pretty low priority I think but would be cool to handle it nicer!

**Comment by isacikgoz** [comment]
Hey @CGA1123 , thanks for the feedback. I am very surprised that how did I haven't got this while using on my own. I think it is a potential issue, so I quickly pushed a patch for it 👍

**Comment by CGA1123** [comment]
@isacikgoz Awesome! :)
